config/routes.rb
Rails.application.routes.draw do
  
  root to: "articles#index"
  
  get 'home/index'
  
  get 'terms' => 'pages#terms'

  get 'about' => 'pages#about'

  devise_for :users

  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  
  resources :articles do
    resources :comments, only: [:create]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true, length: {minimum: 3, maximum: 140}
  validates :text, presence: true, length: {minimum: 10, maximum: 4000}

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :body, presence: true, length: {minimum: 3, maximum: 4000}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create]

  def index
    @articles = Article.order('created_at DESC')
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :author)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    if @comment.save 
      redirect_to @article
    else
      @article = Article.find(params[:article_id])
      @comment_flash = 'Type something in the field (minimum 3 chars)'
      render "articles/show"
    end
    
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new contact_params
    if @contact.valid?
      @contact.save
      flash[:notice] = "Ваше сообщение отправлено, спасибо за отзыв!"
      redirect_to new_contacts_path   
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
    
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    sentence = I18n.t("errors.messages.not_saved",
                    count: resource.errors.count,
                    resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      <p style="font-size: 20px">#{sentence}</p>
      <ul>#{messages}</ul>
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1><%= t('headers.articles.article_edit', number: @article.id) %></h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<div class="form-group">
		<%= f.label :title %> 
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :text %> 
		<%= f.text_area :text, class: "form-control", rows: "6" %>
	</div>
	<p><%= f.submit 'Save', class: "btn btn-primary" %></p>
<% end %>

app/views/articles/index.html.erb
<h1><%= t('headers.articles.article_index') %></h1>

<article>
	<% @articles.each do |a| %>
		<h3><%= link_to a.title, article_path(a) %></h3>
		<div class="row">
			<div class="col-md-7 col-xs-12">
				<span class="glyphicon glyphicon-time"></span> Создан: <%= a.created_at.localtime.strftime('%d-%m-%Y %H:%M') %>
			</div>
			<div class="col-md-5 col-xs-12">
				<div class='pull-right'>
					<span class="glyphicon glyphicon-user"></span> Автор: <%= a.author %> 
                	<span class="glyphicon glyphicon-pencil"></span> Комментариев: <%= a.comments.count %>
                </div>
        	</div>
		</div>
		<br/><img src="img/900x300.jpg" class="img-responsive"><br/>
		<%= a.text %>
		<br/><br/>
					
		<p class="text-right"><%= link_to "Подробнее...", article_path(a) %></p>
			
		<hr/>
	<% end %>
</article>

<nav>
	<ul class="pager">
		<li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Older</a></li>
		<li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
	</ul>
</nav>

app/views/articles/new.html.erb
<h2><%= t('headers.articles.article_new') %></h2>

<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
			<% @contact.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</p>
<% end %>

<%= form_for :article, url: articles_path do |f| %>
	<%= f.hidden_field :author, value: current_user.username %>
	<div class="form-group">
		<%= f.label :title, "Заголовок" %>
		<%= f.text_field :title, class: "form-control", placeholder: "Текст заголовка" %>
	</div>
	<div class="form-group">
		<%= f.label :text, "Текст" %> 
		<%= f.text_area :text, class: "form-control", rows: "6", placeholder: "Текст статьи" %>
	</div>
	<p><%= f.submit "Опубликовать", class: "btn btn-primary" %></p>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<%= @article.text %>
<hr/>

<% if user_signed_in? && @article.author == current_user.username %>
	<p class="text-right"> 
		<%= link_to "Редактировать", edit_article_path(@article) %> |
		<%= link_to "Удалить", @article, method: :delete, data: { confirm: 'Are you sure?'} %>
	</p>
<% end %>

<h3>Комментарии:</h3>
<% @article.comments.each do |с| %>
	<i><%= с.author %> сказал:</i><br/>
	<%= с.body %>
	<hr/>
<% end %>

<% if !@comment_flash.nil? %>
	<div class="alert alert-warning" id="fl1">
		<a href="#" data-dismiss="alert" class="close">×</a>
		<%= @comment_flash %>
	</div>
<% end %>

<% if !current_user.nil? %>
	<%= form_for([@article, @article.comments.build]) do |f| %>
		<%= f.hidden_field :author, value: current_user.username %>
		<div class="form-group">
			<%= f.label :body, "Добавить комментарий" %><br/>
			<%= f.text_area :body, class: "form-control", rows: "4", placeholder: "Текст комментария" %>
		</div>
		<p><%= f.submit "Добавить", class: "btn btn-primary btn-sm" %></p>
	<% end %>
<% else %>
	<h4>Чтобы добавить комментарий вы должны авторизоваться</h4>
<% end %>

<script type="text/javascript">

	$("body").scrollTop($("#fl1").position().top);

</script>

app/views/contacts/new.html.erb
<h2><%= t('headers.contacts.contact_us') %></h2>

<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
			<% @contact.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</p>
<% end %>

<%= form_for :contact, url: contacts_path do |f| %>
	<div class="form-group">
		<%= f.label :email, "e-mail" %> 
		<%= f.text_field :email, class: "form-control", placeholder: "ivanov@mail.com" %>
	</div>
	<div class="form-group">
		<%= f.label :message, "Ваше сообщение" %>
		<%= f.text_area :message, class: "form-control", placeholder: "Текст сообщения", rows: "4" %>
	</div>
	<p><%= f.submit 'Отправить сообщение', class: "btn btn-primary btn-sm" %></p>
<% end %>

app/views/home/index.html.erb
<h1><%= t('headers.home.home_index') %></h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_flash_messages.html.erb
<!-- Flash messages tree -->

<% if notice %>
	<!-- Override devise native class -->
	<div class="alert alert-success" role="alert">
		<a href="#" data-dismiss="alert" class="close">×</a>
		<%= notice %>
	</div>
<% elsif alert %>
	<!-- Override devise native class -->
	<div class="alert alert-danger" role="alert">
		<a href="#" data-dismiss="alert" class="close">×</a>
		<%= alert %>
	</div>
<% else %>
	<!-- Standart bootstrap flashes -->
	<% flash.each do |message_type, message| %>
	    <div class="alert alert-<%= message_type %>">
	    	<a href="#" data-dismiss="alert" class="close">×</a>
	    	<%= message %>
	    </div>
	<% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse-1" aria-expanded="false">
                	<span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <%= link_to root_path, class: "navbar-brand" do %>
					<span class="glyphicon glyphicon-globe"></span>
				<% end %>

</div>

<nav class="collapse navbar-collapse" id="nav-collapse-1">
            	
    <p class="navbar-text navbar-right">
       	<% if user_signed_in? %>
			<%= t('navbar.nav_who') %> <b><%= current_user.username %></b> | 
			<%= link_to t('navbar.nav_sign_out'), destroy_user_session_path, method: :delete, class: "navbar-link" %>
		<% else %>
			<%= link_to t('navbar.nav_sign_in'), new_user_session_path, class: "navbar-link" %>
		<% end %>
	</p>
                	   	
    <%= form_tag({action: 'index', controller: '/home'}, {method: "get", class: "navbar-form navbar-right"}) do %>
    	<div class="form-group">
  			<%= text_field_tag(:search_input, nil, :placeholder => t('navbar.nav_search_placeholder'), :class => "form-control") %>
  		</div>
  		<%= button_tag(t('navbar.nav_search_button'), :class => "btn btn-default") %>
	<% end %>

    <ul class="nav navbar-nav">
        <li><%= link_to t('navbar.nav_home'), root_path %></li>
        <li><%= link_to t('navbar.nav_contact'), new_contacts_path %></li>
        <li><%= link_to t('navbar.nav_new_article'), new_article_path %></li>
        <li><%= link_to t('navbar.nav_about'), about_path %></li>
        <li><%= link_to t('navbar.nav_terms'), terms_path %></li>
        <li><%= link_to "home/index", home_index_path %></li>
    </ul>
                
</nav>

app/views/layouts/_sidebar.html.erb
<!-- Vidget with subscribe -->
<div class="well text-center">
    <p class="lead">
    	Не хочешь пропускать новые посты? Тогда жми на кнопку!
    </p>
    <button class="btn btn-success">Подписаться</button>
</div>

<!-- Vidget with random posts -->
<div class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Panel title</h3>
	</div>
	<div class="panel-body">
		<ul class="list-group">
	        <li class="list-group-item"><a href="singlepost.html">1. Aries Sun Sign March 21 - April 19</a></li>
	        <li class="list-group-item"><a href="singlepost.html">2. Taurus Sun Sign April 20 - May 20</a></li>
	        <li class="list-group-item"><a href="singlepost.html">3. Gemini Sun Sign May 21 - June 21</a></li>
	        <li class="list-group-item"><a href="singlepost.html">4. Cancer Sun Sign June 22 - July 22</a></li>
	        <li class="list-group-item"><a href="singlepost.html">5. Leo Sun Sign July 23 - August 22 </a></li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Bootstrap scale for platforms -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Meta info --> 
  <meta name="description" content="Blog with Rails">
  <meta name="author" content="Alexander Zhadnov">

  <!-- Project name -->
  <title>RailsBlog</title>

  <!-- Rails service files -->
  	<!-- Service javascript frameworks connection -->
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<!-- Cross-site request forgery protection -->
  	<%= csrf_meta_tags %>
  	
  <!-- Bootstrap JS file -->
  <%= javascript_include_tag "/bootstrap-3.3.6/js/bootstrap.min" %>

  <!-- Bootstrap CSS files --> 
  <%= stylesheet_link_tag "/bootstrap-3.3.6/css/bootstrap.min", "/bootstrap-3.3.6/css/bootstrap-theme.min" %>

  <!-- Rails application css file (goes after Bootstrap to override it) -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>

<body>

	<!-- Navigation bar -->
	<header class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
	        <%= render "layouts/navbar" %>
        </div>
	</header>

	<div id="body" class="container">
		
		<!-- Main page -->	
		<div class="row">

			<!-- Main content part -->
			<div class="col-md-9">
				<%= render "layouts/flash_messages" %>
				<%= yield %>
			</div>
			
			<!-- Side bar -->
			<div class="col-md-3">
				<%= render "layouts/sidebar" %>
			</div>

		</div>
	
	</div>

	<footer>
		<div class="container">
        	-- Copyright information --
        </div>
    </footer>
</body>
</html>

app/views/pages/about.html.erb
<h1><%= t('headers.pages.page_about') %></h1>

app/views/pages/terms.html.erb
<h1><%= t('headers.pages.page_terms') %></h1>